### ISSUE TITLE
FFmpeg support

### ISSUE THREAD

**Issue by filfat** [devkitPro/pacman-packages#30] opened 2018-05-23 15:28 UTC
Would be amazing if we could have access to FFmpeg from libnx.

**Comment by carstene1ns** [comment] 2018-06-25 23:45
Some notes from IRC:
- Building ffmpeg with external libraries needs a change to the `pkg-config` wrapper.
- Building with network support fails currently, because of redefined/missing stuff.
- Building with assembly enabled makes linking fail with errors related to relocations

I have a minimal build which needs testing on hardware: [ffmpeg PKGBUILD](https://github.com/carstene1ns/devkitpro-pacman-packages/blob/switch-ffmpeg/switch/ffmpeg/PKGBUILD).
Used a wrapper library (kitchensink) here, but it failed (and crashed).

**Comment by WinterMute** [comment] 2018-06-26 09:03
I was trying this a couple of days ago configured with
```
    ./configure --prefix="${PORTLIBS_PREFIX}" \
      --enable-cross-compile --cross-prefix=aarch64-none-elf- \
      --pkg-config=/opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-pkg-config \
      --disable-shared --disable-runtime-cpudetect --disable-armv5te --disable-programs \
      --disable-doc --disable-everything -enable-decoder='mpeg4,h264,aac,ac3,mp3,theora,ogg,flac,vorbis' \
      --enable-demuxer='mov,h264,ogg,flac' --enable-filter='rotate,transpose' --enable-protocol='file,http' \
      --enable-static --enable-small --arch=armv8a --cpu=cortex-a57 --disable-armv6t2 --target-os=none \
      --extra-cflags='-D__SWITCH__ -O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec' \
      --extra-cxxflags='-D__SWITCH__ -O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec' \
      --extra-ldflags='-fPIE -L${PORTLIBS_PREFIX}/lib -L${DEVKITPRO}/libnx/lib' --disable-iconv --disable-lzma \
      --disable-securetransport --disable-xlib
```

I'm not seeing any issue with our pkg-config wrapper although I did have to specifically tell ffmpeg to use it.

The network support issue looks like it's caused by some configure tests failing which should be passing. Might need to patch configure so it adds -lx to network_extralibs for us - I've attempted to set variables externally but without success so far.

I don't like this `WARNING: Compiler does not indicate floating-point ABI, guessing soft. `

Did you patch something else? It failed on me attempting to compile arm assembly but I'm probably missing some configure option.

I'd suspect that relocation errors are from something missing -fPIC somewhere.

**Comment by WinterMute** [comment] 2018-07-06 15:52
I'm not seeing any issue building this https://github.com/devkitPro/pacman-packages/tree/switch-ffmpeg/switch/ffmpeg

need something to test with though

**Comment by tiliarou** [comment] 2018-07-31 05:15
Yes it builds and installs properly (although a few deprecated warning message).
Any luck in testing it ?

**Comment by VelocityRa** [comment] 2018-10-08 01:45
Why is this still not merged?
I thought https://github.com/XorTroll/PlayerNX was based on it, so it's tested.

**Comment by WinterMute** [comment] 2018-10-08 07:36
@VelocityRa because apparently it's too much to ask that people actually report back on whether or not things work ...

**Comment by WinterMute** [comment] 2018-10-08 16:45
What changes did you make to the args?

**Comment by XorTroll** [comment] 2018-10-13 21:03
I don't have the changed PKGBUILD, but I think I deleted two or three build arguments. Anyway, the one you posted failed to find switch-libass, but I already had it installed. Maybe it was my fault

**Comment by K3yn** [comment] 2018-11-02 08:56
i build this today and finc, ty WinterMute

**Comment by VelocityRa** [comment] 2018-11-09 00:49
Can this be merged now please?

**Comment by RicBent** [comment] 2018-11-12 17:08
This does not work for me unless I remove
`--enable-libfreetype --enable-libass --enable-libfribidi`
even though I have these installed, similar to what @XorTroll reported.

**Comment by K3yn** [comment] 2018-11-12 19:04
this work for me, but not is an usual process for compile,
dont remove any lane, this work.
If u want, search me in 4tu discord channel or in gbatemp and explain u for compile...........

**Comment by VelocityRa** [comment] 2018-11-12 19:42
@K3yn Why not just explain what you did here for everyone?

**Comment by K3yn** [comment] 2018-11-12 20:14
oks, just download https://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2.
Untar in a folder and place u with msys2 inside.
Now modify pkgbuild .........

copy this and paste in msys2

pkgname=switch-ffmpeg
pkgver=4.1
pkgrel=1
pkgdesc='ffmpeg port (for Nintendo Switch homebrew development)'
arch=('any')
url='https://ffmpeg.org/'
license=('LGPL' 'GPL')
options=(!strip staticlibs)
makedepends=('switch-pkg-config' 'devkitpro-pkgbuild-helpers')
depends=('switch-zlib' 'switch-bzip2' 'switch-libass' 'switch-libfribidi'
         'switch-freetype' 'switch-libtheora')
source=("https://ffmpeg.org/releases/ffmpeg-$pkgver.tar.xz")
sha256sums=('605f5c01c60db35d3b617a79cabb2c7032412be243554602eeed1b628125c0ee')
groups=('switch-portlibs')
export DEVKITPRO=/opt/devkitpro
export PORTLIBS_ROOT=${DEVKITPRO}/portlibs
export PATH=${DEVKITPRO}/tools/bin:${DEVKITPRO}/devkitA64/bin:$PATH
export TOOL_PREFIX=aarch64-none-elf-
export AR=${TOOL_PREFIX}gcc-ar
export RANLIB=${TOOL_PREFIX}gcc-ranlib
export PORTLIBS_PREFIX=${DEVKITPRO}/portlibs/switch
export PATH=$PORTLIBS_PREFIX/bin:$PATH
export CFLAGS="-O2 -ffunction-sections -fdata-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec"
export CXXFLAGS="${CFLAGS}"
export CPPFLAGS="-D__SWITCH__ -I ${PORTLIBS_PREFIX}/include -isystem ${DEVKITPRO}/libnx/include"
export LDFLAGS="-O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -L${PORTLIBS_PREFIX}/lib -L${DEVKITPRO}/libnx/lib"
export LIBS="-lnx"

  ./configure --prefix=$PORTLIBS_PREFIX --disable-shared --enable-static \
    --enable-cross-compile --cross-prefix=aarch64-none-elf-  \
    --arch=aarch64 --target-os=none --enable-pic --disable-asm \
    --extra-cflags='-D__SWITCH__ -O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec' \
    --extra-cxxflags='-D__SWITCH__ -O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec' \
    --extra-ldflags='-fPIE -L${PORTLIBS_PREFIX}/lib -L${DEVKITPRO}/libnx/lib' \
    --disable-runtime-cpudetect --disable-programs --disable-debug --disable-doc \
    --disable-network --disable-hwaccels --disable-encoders \
    --disable-avfilter --disable-avdevice --enable-swscale --enable-swresample \
    --enable-libass --enable-libfreetype --enable-libfribidi --enable-libtheora  --enable-libopus \
    --enable-filter='rotate,transpose' \
    --disable-protocols --enable-protocol=file \
    --disable-demuxers --enable-demuxer=h264,matroska,mov,ogg \
    --disable-decoders --enable-decoder=h264,aac,ac3,mp3,theora,ogg,vorbis \
    --disable-parsers --enable-parser=h264,aac

if all is ok u can make

and after

export DEVKITPRO=/opt/devkitpro
export PORTLIBS_ROOT=${DEVKITPRO}/portlibs
export PATH=${DEVKITPRO}/tools/bin:${DEVKITPRO}/devkitA64/bin:$PATH
export TOOL_PREFIX=aarch64-none-elf-
export AR=${TOOL_PREFIX}gcc-ar
export RANLIB=${TOOL_PREFIX}gcc-ranlib
export PORTLIBS_PREFIX=${DEVKITPRO}/portlibs/switch
export PATH=$PORTLIBS_PREFIX/bin:$PATH
export CFLAGS="-O2 -ffunction-sections -fdata-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec"
export CXXFLAGS="${CFLAGS}"
export CPPFLAGS="-D__SWITCH__ -I ${PORTLIBS_PREFIX}/include -isystem ${DEVKITPRO}/libnx/include"
export LDFLAGS="-O2 -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -L${PORTLIBS_PREFIX}/lib -L${DEVKITPRO}/libnx/lib"
export LIBS="-lnx"
make DESTDIR="ffmpeg-4.0.21" install
rm -r "ffmpeg-4.0.21"${PORTLIBS_PREFIX}/share

this make a folder called ffmpeg-4.021 inside main folder ffmpeg........
Inside this folder /opt/devkitpro/portlibs/switch
two folders, include and lib, copy and paste this in your installation folder of devkitpro

and try to compile.................example PlayerNx..........

**Comment by K3yn** [comment] 2018-11-12 20:15
Sorry for my english :)

**Comment by WinterMute** [comment] 2018-11-13 09:51
I've merged this now and deleted horrifically inappropriate instructions.

Please don't do this without consulting toolchain maintainers. It causes serious grief when we have to help novices unravel the damage.

In some cases people have had to reinstall their operating systems to fix problems caused by bodges to the toolchain installs.

**Closed by WinterMute** 2018-11-13 09:51 UTC
Labels: enhancement

**Comment by WinterMute** [comment] 2018-11-14 20:45
Meant to post this here too.

Please note that providing bogus build instructions and/or building these things manually without any feedback to the toolchain maintainers hinders more than it helps. There are limited hours in the day and I could really do with spending fewer of them helping newbies unravel the damage caused by random tutorials with instructions to inappropriately modify the toolchain and/or supporting libraries to bodge around a complete lack of understanding how these things interoperate.

We can generally be found via the venues listed at https://devkitpro.org/wiki/Community_Portal

We don't do Discord, reddit or pirate forums and users in those venues will often supply poor advice.
